### ISSUE TITLE
Having Trouble in diy the env

### ISSUE THREAD

**Issue by W-Zhi-Chao** [shacklettbp/madrona#41]
Hello Authors, It's amazing for me to see overcooked env running such fast.
Actually, I am trying to modify the environment so that the Python interface can access more environmental information. 
The codebase of the env is in **https://github.com/Stanford-ILIAD/Diverse-Conventions/tree/neurips_comedi/src/overcooked2_env**
After some code reading, I noticed that maybe I can add "**exportTensor**" logic to return more information from the parallel env. I made the following modifications:
1. **In mgr.cpp: add**
MADRONA_EXPORT Tensor Manager::**timeTensor**() const
{
    return impl_->exportTensor(**6**, Tensor::ElementType::Int32,
        {impl_->cfg.num_players, impl_->cfg.numWorlds});
}
2. **In mgr.hpp: add**
MADRONA_IMPORT madrona::py::Tensor timeTensor() const;
3. **In sim.cpp: add**
registry.exportColumn<Agent, Time>(6);
4. **In sim.hpp: add**
struct Time {
        int32_t rew_time;
};

After I rebuild the code and run the env, I get the error:
**an illegal memory access was encountered**
I cannot trace the error, it just tells me this line of code has crashed:
**inline virtual ~GPUImpl() final
  {
      REQ_CUDA(cudaFree(episodeMgr));
  }**
Any Ideas or Debugging Suggestions? Thanks!

**Comment by shacklettbp** [comment]
You most likely need to increase this variable, since you've increased the number of exported buffers: https://github.com/Stanford-ILIAD/Diverse-Conventions/blob/neurips_comedi/src/overcooked2_env/mgr.cpp#L186

General debugging tips:
1) Test on the CPU
2) Run under cuda-gdb instead of regular gdb
3) use the MADRONA_MWGPU_FORCE_DEBUG=1 environment variable (along with cuda-gdb) to make debugging easier (disables compiler optimizations, code will be much much slower but more straightforward to step through).

**Comment by W-Zhi-Chao** [comment]
After Increasing the number of num_exported_buffers, I got this error:
**RuntimeError: The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.**
I cannot understand it.
